tilemap:
  url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
  options:
    attribution: '&copy; [OpenStreetMap]("http://www.openstreetmap.org/copyright")'
    subdomains:
      - a
investigate_access_control:
  admin_role: kibiadmin
  sirenalert:
    username: sentinl
elasticsearch:
  username: kibiserver
